name:                http2-grpc-proto3-wire
version:             0.1.0.0
github:              "higherkindness/http2-grpc-haskell"
license:             BSD3
author:              "Alejandro Serrano"
maintainer:          "lucas@dicioccio.fr"
copyright:           "2019 Alejandro Serrano"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Encoders based on `proto3-wire` for gRPC over HTTP2.
category:            Network

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/higherkindness/http2-grpc-haskell#readme>

dependencies:
- base >= 4.11 && < 5
- http2-grpc-types
- binary >= 0.8.5 && < 0.11
- bytestring >= 0.10.8 && < 0.11
- case-insensitive >= 1.2.0 && < 1.3
- zlib >= 0.6.2 && < 0.7
- proto3-wire >= 1 && < 1.1

library:
  source-dirs: src
  ghc-options: -Wall
